org.openqa.selenium.WebDriverException: com.gargoylesoftware.htmlunit.ScriptException: missing ; before statement (http://35.246.92.202/js/contacts.js#31) Still attempting HtmlUnit.